Update main to match 5.x maintenance
fcrepo-exts/fcrepo-java-client pull request #58
Opened 2021-05-08 15:27 UTC by bbpennel

2021-05-10 15:20 UTC, dbernstein commented
@bbpennel :  I think it is better if the new version (ie in HEAD) is 5.1.0-SNAPSHOT rather than 5.0.0-SNAPSHOT.

2021-05-12 12:36 UTC, bbpennel commented
@dbernstein updated

2021-05-17 21:08 UTC, dbernstein approved these changes

2021-05-17 21:09 UTC, dbernstein requested changes

2021-05-17 21:09 UTC, dbernstein commented on pom.xml
>    <name>Fedora 4 Java Client Libraries</name>
@bbpennel :  could you remove  the "4" from "Fedora 4 Client Libraries"?

2021-05-17 21:28 UTC, dbernstein approved these changes

2021-05-17 21:28 UTC, merged