Update the client to run against Fedora 6
fcrepo-exts/fcrepo-java-client pull request #59
Opened 2021-05-13 20:08 UTC by dbernstein

**Update the client to run against Fedora 6**
* * *

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3672

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)

# What does this Pull Request do?
* Updates to support Fedora 6.
* Use fcrepo.war instead of spring configs for integration tests
* Remove deprecated functions (move and copy)

# How should this be tested?

Covered by unit and integration tests.

# Additional Notes:
There are two tests that were @Ignored in FcrepoClientIT.  I wasn't sure what needed to be done there. @bbpennel if you wouldn't mind taking a look at that I would appreciate it.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers

2021-05-13 20:10 UTC, dbernstein commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +    @Ignore("fix me")
I wasn't sure what the proper fix should be here.

2021-05-13 20:10 UTC, dbernstein commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +    @Ignore("fix me")
Here as well.

2021-05-17 22:03 UTC, bbpennel requested changes

2021-05-18 16:40 UTC, bbpennel commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +        // try to update without lenient header // fedora 6 is lenient by default.
I was actually suggesting removing the other part, but I guess it doesn't matter that much

2021-05-18 20:51 UTC, bbpennel approved these changes

2021-05-18 20:52 UTC, merged