WIP: FCREPO-3704: Close internally used ClosableHttpClient instance
fcrepo-exts/fcrepo-java-client pull request #61
Opened 2021-05-20 17:29 UTC by tomcbe

**Close internally used ClosableHttpClient instance**
* * *

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3704

# What does this Pull Request do?
Properly close the internally used instance of CloseableHttpClient when FcrepoClient is closed.

# What's new?
* Implements the Closeable interace for FcrepoClient
* Closes the internally used instance of CloseableHttpClient in FcrepoClient in the newly added close() method.

# How should this be tested?
* Existing tests demonstrate, that this change as no effect on usage of FcrepoClient

# Additional Notes:
* Currently there is no Test that explicitly tests, if the CloseableHttpClient has been closed

# Interested parties
@dbernstein

2021-05-20 17:35 UTC, tomcbe commented
@dbernstein This is my current progress regarding FCREPO-3704.

I still have some open questions:
* How do we communicate to users that they should close any instances of FcrepoClient, when no longer needed?
* We currently use reflection (see method `TestUtils.setField`) to set the private field httpClient in FcrepoClient in some tests. But this always leaves a unmanaged instance of ClosableHttpClient that is never closed during tests. Do you see a proper way to tackle this problem?

2021-10-29 20:27 UTC, dbernstein commented
@tomcbe :  sorry - this PR fell off my radar.  As I'm getting ready to release the code, I see this still needs addressing.

Re question 1:  so this PR closes a connection that what was previously unclosed yes?  In that case I would not expect any side effects for any code that depends on the fcrepo java client.  Is that your understanding?  Regarding telling users knowing about this `close` feature,  I would just add  a note to the readme.

Re question 2:  I'm not sure that this matters.  Am I missing something?

2021-10-29 20:28 UTC, dbernstein approved these changes

2021-11-03 12:45 UTC, tomcbe commented
> @tomcbe : sorry - this PR fell off my radar. As I'm getting ready to release the code, I see this still needs addressing.
> 
> Re question 1: so this PR closes a connection that what was previously unclosed (unless someone supplied their own httpclient) yes? In that case I would not expect any side effects for any code that depends on the fcrepo java client. Is that your understanding? Regarding telling users knowing about this `close` feature, I would just add a note to the readme.

Well in order to actually close the underlying HttpClient instance users should either use FcrepoClient in a try-with-resources block or call FcrepoClient.close() explicitly once they don't need it anymore.

> 
> Re question 2: I'm not sure that this matters. Am I missing something?

I guess it shouldn't have any effects on the outcome of the tests, but would at least be best practice to also manage resources properly in integration tests.

2021-11-04 11:14 UTC, tomcbe commented
Hi @dbernstein 
The integration tests needed a refactoring after all. Before that the normally were just hanging at some point because non of the FcrepoResponse objects where properly closed.

Could you please take another look?

2021-11-04 20:47 UTC, bbpennel requested changes
A few minor questions/suggestions, but over all it looks good to me.

2021-11-04 20:47 UTC, bbpennel commented on src/test/java/org/fcrepo/client/integration/FcrepoAuthenticationIT.java
> +        try (final FcrepoResponse response = unauthClient.get(new URI(SERVER_ADDRESS)).perform()) {
It looks like this method is still ignored, and the ticket it references is "Won't Fix". I wonder if we should re-enable it or delete it. It apparently does not pass

2021-11-04 20:47 UTC, bbpennel commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +            createdRessourceUri = response.getLocation();
```suggestion
            createdResourceUri = response.getLocation();
```

2021-11-04 20:47 UTC, bbpennel commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +        final URI ressourceLocation;
```suggestion
        final URI resourceLocation;
```

2021-11-04 20:47 UTC, bbpennel commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +        final URI createdRessourceUri;
```suggestion
        final URI createdResourceUri;
```

2021-11-04 20:47 UTC, bbpennel commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +        final URI createdRessourceUri;
```suggestion
        final URI createdResourceUri;
```

2021-11-05 10:31 UTC, tomcbe commented on src/test/java/org/fcrepo/client/integration/FcrepoAuthenticationIT.java
> +        try (final InputStream body = new ByteArrayInputStream(rdfTtl.getBytes())) {
Thanks for the hint. I removed the try-with-resources-blocks for the ByteArrayInputstreams in with the last commit.

2021-11-05 10:31 UTC, tomcbe commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +            createdRessourceUri = response.getLocation();
Fixed locally

2021-11-05 10:31 UTC, tomcbe commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +        final URI ressourceLocation;
Fixed locally

2021-11-05 10:32 UTC, tomcbe commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +        final URI createdRessourceUri;
Fixed locally

2021-11-05 10:32 UTC, tomcbe commented on src/test/java/org/fcrepo/client/integration/FcrepoClientIT.java
> +        final URI createdRessourceUri;
Fixed locally

2021-11-05 12:11 UTC, bbpennel approved these changes

2021-11-05 15:36 UTC, merged